appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: U4MGZZ7zszZkWg25eeuLEFepDchXZe/Mw8cXMmLQDZrf9Tu5wr5NzuadZlFhLpL3/kwA1Zs0VrokxlBCuqTtrozao08k7k6qzDcb6xc67Fv+6Sdqh6PFjnbMiK5wWbk3YgBZjzAVRJeXCJGiW2cj3CWFGzqSZ400tMYUytyf1I3HhWilW7j/rCMNGvgyBh0J3UYpfd9C7gALmMvpwnDNJMuE7W0evxy0vGHNe8rwjC1UXXIqd47eURQOo948+ITN6pSzOE3dvWoiBqFAS30udIHyPNjtCAk8JhLCREBU97fBl4hIjadkcIWv8BwpkSeZIcMJf9pPONVV5/tgoGzZ14Dr+82mn9BxVQP6sYf8FhpNwx5Y/51+SrdRjQvHzgO0xyH8J9FUC7ENlO33OOKWhTuxaWx4kB+PF4kUq2vctKUbhFrL4ySxAoJ5b1CAJxoIHyBRX6PrGyO+mlF6kF/CK2LFyH+G7s8o7UZlnrsENmYp2q3YPPSPRouT9KhrlNJlf+GJ1q+bsdvMuoMLGG5kWAZD874szPEbKO0Iihxf90JGpGrX239nAhFPrE5CjllMImcMsv6yswkWow86rqPwcGTVe6rL1A05u66OofwVJkBpTRM9fGZtO7r4V2yKRWSkXPF1plb29o1Y3i0OGNtTr6RnOME6tqEF3U9zVR3ywY0=}
bot:
  automerge: true
