travis:
  secure:
    BINSTAR_TOKEN: QNoHinwjhwuf0AGa5H+VI0b9TnDVQp2u59SIgMR2zHBXs1PFssSjeDvHdOjjPfqWD1Mh5Iab82W4/XCLs6bDJu5khGKiotQTr3xE8hD/MZ0qWkP0BITw4ECb6fu30Zf96bZhessqJqkbKTmHYXuNSRgplJOAnysVNpJBljD6f/GSltb2iw0/yWVDX4TBsbk+1nBdDkczXb8Z8k+WiXlx9C3bJQkBpzI63Pfu//vP+7Am6M5emR955DrU72QhL3cmWccSoByGlfQ3ysCSET7yWKFprwx6X8CfRsW/NCNYKbgmpD978Z0pSQzd6s1neATYDF/2XfCIY5cuJJeyDhna0xDtgSkx256KcM+ywE1zeXov/jHjHXe8oioZG3R3bC9Pxf+UBOAwJcouQAfu012ElRUbRWlmp9B03Q+8CYmj65NDg27gNybq2AhbHxnI2yki0a9RUL2dFuewtwonPeO/nTVDCdTbmKGdMrG5kF5eufkhahDIyNqVZUd2EOPMESYvRHCeBbo1SXMsNqLHZr1Qm00tiPtP+0Mk4rXFB8t3yk9g7lX97gIo6wdveZFjL7gelN77hCFoBu/MoueFRzmxUtuHnDUXumEEH/QF1FRWh06dPq9jDXB+yRUoXijBXtmO2JVtjVIPpOWfpl09Y1I1FXgfwhm+Yj4DniCQ7sO0zLY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
